device_connected: true
cpu: "X64"
system: "LINUX"
robot:
  name: "GR1"
  mechanism: "T2"
  control_period: 0.01
  input_and_calculate_period: 0

  # right now, the state estimator is not very accurate, suggest to disable it
  # unless you know what you are doing
  state_estimator:
    enable: false
    path: "/state_estimator/model_gr1_t2.json"

comm:
  enable: false
  use_raw: false
  use_json: false
  use_dds: false
  use_sim: false

operator:
  use_joystick: false
  joystick_connected: false
  joystick_type: "XBOX"  # support "XBOS", "PS4", "PS5"
  use_keyboard: false
  keyboard_connected: false

ota:
  enable: false

hardware:
  use_can: false
  use_ethernet: false
  use_etherbus: false
  use_fi_fse: true
  use_fi_fsa: true

sensor_usb_imu:
  usb: [
    "/dev/ttyUSB0"
  ]
  comm_enable: [
    false
  ]
  comm_frequency: [
    500
  ]

sensor_abs_encoder:
  type: "FIFSEV1"
  ip: [
    # left leg
    "192.168.137.170", "192.168.137.171", "192.168.137.172", "192.168.137.173", "192.168.137.174", "192.168.137.175",
    # right leg
    "192.168.137.150", "192.168.137.151", "192.168.137.152", "192.168.137.153", "192.168.137.154", "192.168.137.155",
    # waist
    "192.168.137.190", "192.168.137.191", "192.168.137.192",
  ]
  data_path: "sensor_offset.json"

fi_fse:
  version: "v1"

fi_fsa:
  version: "v1"
  debug: false
  blocking: false
  timeout: 0.01
  port_ctrl: 2333
  port_comm: 2334
  port_fast: 2335
  network: "192.168.137.255"
  concurrency: true

actuator:
  type: "FIFSAV1"
  use_dic: false
  names: [
      "l_hip_roll", "l_hip_yaw", "l_hip_pitch", "l_knee_pitch", "l_ankle_pitch", "l_ankle_roll",
      "r_hip_roll", "r_hip_yaw", "r_hip_pitch", "r_knee_pitch", "r_ankle_pitch", "r_ankle_roll",
      "joint_waist_yaw", "joint_waist_pitch", "joint_waist_roll",
      "joint_head_pitch", "joint_head_roll", "joint_head_yaw",
      "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow_pitch", "l_wrist_yaw", "l_wrist_roll", "l_wrist_pitch",
      "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow_pitch", "r_wrist_yaw", "r_wrist_roll", "r_wrist_pitch",
  ]
  ip: [
    # left leg
    "192.168.137.70", "192.168.137.71", "192.168.137.72", "192.168.137.73", "192.168.137.74", "192.168.137.75",
    # right leg
    "192.168.137.50", "192.168.137.51", "192.168.137.52", "192.168.137.53", "192.168.137.54", "192.168.137.55",
    # waist
    "192.168.137.90", "192.168.137.91", "192.168.137.92",
    # head
    "192.168.137.93", "192.168.137.94", "192.168.137.95",
    # left arm
    "192.168.137.10" , "192.168.137.11" , "192.168.137.12" , "192.168.137.13" , "192.168.137.14" , "192.168.137.15" , "192.168.137.16",
    # right arm
    "192.168.137.30" , "192.168.137.31" , "192.168.137.32" , "192.168.137.33" , "192.168.137.34" , "192.168.137.35" , "192.168.137.36",
  ]
  comm_enable: [
    # left leg
    false, false, false, false, false, false,
    # right leg
    false, false, false, false, false, false,
    # waist
    true, true, true,
    # head
    true, true, true,
    # left arm
    true, true, true, true, true, true, true,
    # right arm
    true, true, true, true, true, true, true,
  ]
  comm_use_fast: [
    # left leg
    true, true, true, true, true, true,
    # right leg
    true, true, true, true, true, true,
    # waist
    true, true, true,
    # head
    true, true, true,
    # left arm
    true, true, true, true, true, true, true,
    # right arm
    true, true, true, true, true, true, true,
  ]
